export const site = {
  name: "Cloud Bun Bakery LLC",
  description:
    "Cloud Bun Bakery LLC is a Kentucky home bakery making Filipino favorites including ensaymada, pandesal, Spanish bread, cookies, muffins, and scones for local pickup.",
  keywords: [
    "Cloud Bun Bakery",
    "Cloud Bun Bakery LLC",
    "Kentucky bakery",
    "Kentucky home bakery",
    "Filipino bakery Kentucky",
    "Filipino bakes Kentucky",
    "ensaymada Kentucky",
    "pandesal Kentucky",
    "Spanish bread Kentucky",
    "homemade Filipino bread",
    "Filipino desserts Kentucky",
    "bakery pickup Kentucky",
    "custom bakery boxes",
    "fresh baked scones",
    "chocolate crinkles",
    "homestyle Filipino bakery Kentucky",
    "Filipino home bakery near me",
    "Kentucky Filipino desserts",
    "Kentucky Filipino bread",
    "homemade ensaymada",
    "ube ensaymada Kentucky",
    "classic ensaymada",
    "fresh pandesal",
    "malunggay pandesal",
    "ube pandesal",
    "homemade Spanish bread",
    "Filipino chocolate crinkles",
    "banana muffins Kentucky",
    "blueberry scones Kentucky",
    "strawberry scones Kentucky",
    "bakery boxes Kentucky",
    "preorder bakery Kentucky",
    "pickup bakery Kentucky",
    "small batch bakery Kentucky",
    "home baked Filipino pastries",
    "Filipino treats Kentucky",
    "fresh baked Filipino favorites",
  ],
  // Set the public HTTPS domain before publishing. No backend credentials are needed.
  url: "",
  instagram: "https://www.instagram.com/cloudbunbakery/",
  facebook: "https://www.facebook.com/p/Cloud-Bun-Bakery-LLC-61592804541512/",
};
